import React, { Component } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
export default function Header(props) {

    return (
        <Head>
            <script href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
            <script rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
            {/* <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" /> */}

            <header className="header">
                <div className="top_header">
                    <div className="container">
                        <div className="row text-center">
                            <div className="col-md-7 info_bx">
                                <p>Experience the Power of Customized Minerals</p>
                            </div>
                            <div className="col-md-5 log_bx">
                                <Link href="#" className="call">
                                    <Image src="/call.png" width={20} height={20} alt='fillerboy' /> +91 81421 01923 
                                </Link>
                                <Link href="#" className="email"> <Image src="/email.png" width={20} height={20} alt='fillerboy'/> info@fillerboy.com </Link>

                            </div>
                        </div>
                    </div>
                </div>
                <div className="bottom_header">
                    <div className="container">
                        <div className="menu">
                            <nav className="navbar navbar-expand-sm">
                                <div className="container-fluid">
                                    <Link className="navbar-brand logo" href="http://0.0.0.0:3000/">
                                        <Image src="/logo.png"  width={150} height={40}  alt='fillerboy' />
                                    </Link>
                                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                                        <span className="navbar-toggler-icon"></span>
                                    </button>
                                    <div className="collapse navbar-collapse " id="collapsibleNavbar">
                                        <ul className="navbar-nav">
                                            <li className="nav-item">
                                                <Link className="nav-link" href="/about">About</Link>
                                            </li>
                                            <li className="nav-item">
                                                <Link className="nav-link" href="/service">Services</Link>
                                            </li>
                                            <li className="nav-item">
                                                <Link className="nav-link" href="/product">Products</Link>
                                            </li>
                                            <li className="nav-item">
                                                <Link className="nav-link" href="/blog">blog</Link>
                                            </li>
                                            {/* <li className="nav-item">
                                                <a className="nav-link" href="/contact">Contact</a>
                                            </li> */}
                                        </ul>
                                    </div>
                                </div>
                            </nav>


                        </div>

                    </div>
                </div>
            </header>

        </Head>

    )

}
